name = "Casual Create"
author = "amazing_fungus"
version = "forge-v1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0b9f43b1f39f1caac86cfe09a313fe64e218965155070848433bf85a4ae26a3"

[versions]
forge = "47.1.47"
minecraft = "1.20.1"
