name = "Casual Create"
author = "amazing_fungus"
version = "forge-v1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51e9a043a52c9cca8266fd3f93ad751df854fb77c74ce73956ccb33ea7995eaa"

[versions]
forge = "47.1.47"
minecraft = "1.20.1"
