name = "Casual Create"
author = "amazing_fungus"
version = "forge-v1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83983a18b863c3e300e3dcaaf1b8394bf671c5ee943b8389e814fa34d297b62e"

[versions]
forge = "47.1.47"
minecraft = "1.20.1"
