name = "Casual Create"
author = "amazing_fungus"
version = "forge-v1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ace2878da9d7853f00c132c55e6c5d15b463625089eaa429d0e42abed331c5b"

[versions]
forge = "47.1.47"
minecraft = "1.20.1"
