name = "Casual Create"
author = "amazing_fungus"
version = "forge-v1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e522ae56e09c9861143b5275a23793fc862291bdb63c482256c8ca40cf250b5"

[versions]
forge = "47.1.47"
minecraft = "1.20.1"
